// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5TOrh8_oUgL0JdzMgujIYxVaTIid2Jo',
    appId: '1:659814777847:web:b387d6d057811c902d64f2',
    messagingSenderId: '659814777847',
    projectId: 'farmingapp-72e88',
    authDomain: 'farmingapp-72e88.firebaseapp.com',
    storageBucket: 'farmingapp-72e88.firebasestorage.app',
    measurementId: 'G-E02DP6G589',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxUY98IiAOZuUhUcoZ2xP702XY1-ILi8',
    appId: '1:659814777847:android:9ad354edf01798502d64f2',
    messagingSenderId: '659814777847',
    projectId: 'farmingapp-72e88',
    storageBucket: 'farmingapp-72e88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpZ47p7unTbjxxLB37yViBxOiOiOIe-Zg',
    appId: '1:659814777847:ios:9cc0a79cd0cadd682d64f2',
    messagingSenderId: '659814777847',
    projectId: 'farmingapp-72e88',
    storageBucket: 'farmingapp-72e88.firebasestorage.app',
    iosBundleId: 'com.example.farmingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpZ47p7unTbjxxLB37yViBxOiOiOIe-Zg',
    appId: '1:659814777847:ios:9cc0a79cd0cadd682d64f2',
    messagingSenderId: '659814777847',
    projectId: 'farmingapp-72e88',
    storageBucket: 'farmingapp-72e88.firebasestorage.app',
    iosBundleId: 'com.example.farmingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN5TOrh8_oUgL0JdzMgujIYxVaTIid2Jo',
    appId: '1:659814777847:web:e54eb8f3cfbbe0162d64f2',
    messagingSenderId: '659814777847',
    projectId: 'farmingapp-72e88',
    authDomain: 'farmingapp-72e88.firebaseapp.com',
    storageBucket: 'farmingapp-72e88.firebasestorage.app',
    measurementId: 'G-66Z5N490Q6',
  );

}